language: ruby
rvm: 
    - 2.2.5

install: gem install jekyll html-proofer jekyll-sitemap

sudo: required

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

services:
    - docker
  
script:
    - docker build -t 4383/machine .
    - docker run 4383/machine /bin/bash -c "cat .bashrc | grep 'machine auto setup'" | grep "machine"
    - docker ps -a

after_success:
    - chmod +x -R deployment
    - deployment/build.sh
    - deployment/deploy.sh
