sudo: required

services:
  - docker
  
script:
  - docker build -t 4383/machine .
  - docker run 4383/machine /bin/bash -c "cat .bashrc | grep 'machine auto setup'" | grep "machine"
  - docker ps -a
