language: python
python: 3.5

install: pip install -r requirements_dev.txt

sudo: required

services:
  - docker
  
script:
  - bumpversion --verbose minor
  - docker build -t 4383/machine .
  - docker run 4383/machine /bin/bash -c "cat .bashrc | grep 'machine auto setup'" | grep "machine"
  - docker run 4383/machine
  - docker ps -a
